######################################################################
# Automatically generated by qmake (2.01a) Mon Mar 5 14:20:16 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += webkit

# Input
SOURCES += main.cpp
