######################################################################
# Automatically generated by qmake (2.01a) Thu Feb 2 11:09:12 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS = notepad.h
SOURCES = notepad.cpp \
          main.cpp

